### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by hruchka** [hruchka/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by iLoveJesusChrist** [comment]
<section>
									<h3>Languages</h3>
									<p class="tags small">
										<span class="language" lang="en"
											>&#x1f1fa;&#x1f1f8; English</span>
										<span class="language" lang="it"
											> &#x1f1ee;&#x1f1f9; Italiano</span>
									</p>
								</section>
								<section>
									<h3>Skills</h3>
									<p class="tags small">
										<span class="nowrap">PLAYING PIANO</span> SPARKLING
										<span class="nowrap">READING MINDS</span> <br>
										QUICK HEALING
										<span class="nowrap">SUPERHUMAN STRENGHTS</span>
									</p>
								</section>
								<section>
									<h3>Likes&#x1f603;</h3>
									<p class="tags small">
										<span class="nowrap">SPEED</span> BELLA
										<span class="nowrap">BLOOD</span> OVERREACTING
										<span class="nowrap">STALKING</span><br>
										 GOOD CLOTHES
										<span class="nowrap">KILLING ENEMIES</span> ATTACKING
									</p>
								</section>
								<section>
									<h3>Dislikes&#x1f61e;</h3>	
									<p class="tags small">
										<span class="nowrap">HEARTBEAT</span> WEREWOLVES
										<span class="nowrap">SLEEP</span> COUNTRY MUSIC
										<span class="nowrap">NOT BEING ABLE TO READ BELLA’S MIND</span> JACOB
									</p>
								</section>
								<section>
									<h3>Wants&#x1F36F;</h3>
									<p class="tags small bulleted">
										TO TAKE A NAP, 'CAUSE I HAVEN'T TAKEN ONE SINCE SEPTEMBER 1918 
									</p>
								</section>
								<section>
									<h3>Character</h3>
									<p>
										<span class="nowrap">KIND</span> PRINCE CHARMING
										<span class="nowrap">POLITE</span> PROTECTIVE
										<span class="nowrap">A BIT STUBBORN, BUT LOVING GENTLEMAN</span> 
									</p>
								</section>
								<section>
									<h3>Moto</h3>
									<em>"No measure of time with you will be long enough, but we'll start with forever."</em>
								</section>
